export const enum NationalityEnum {
    American = 'United States',
    Australian = 'Australia',
    Austrian = 'Austria',
    Azerbaijani = 'Azerbaijan',
    Baharna = 'Bahrain',
    Belgian = 'Belgium',
    Brazilian = 'Brazil',
    British = 'UK',
    Canadian = 'Canada',
    Chinese = 'China',
    Danish = 'Denmark',
    Dutch = 'Netherlands',
    Emirati = 'UAE',
    Finnish = 'Finland',
    French = 'France',
    German = 'Germany',
    Hungarian = 'Hungary',
    Italian = 'Italy',
    Japanese = 'Japan',
    Mexican = 'Mexico',
    Monegasque = 'Monaco',
    Qatari = 'Qatar',
    'Saudi Arabian' = 'Saudi Arabia',
    Singaporean = 'Singapore',
    Spanish = 'Spain',
    Thai = 'Thailand'
}